stages:
  download_data:
    cmd: python src/data/download.py --config params.yaml
    deps:
    - src/data/download.py
    params:
    - data.bucket
    - data.local_path
    - data.minio_endpoint
    - data.object_key
    outs:
    - data/raw/train.csv

  preprocess_data:
    cmd: python src/preprocess/preprocess.py --config params.yaml
    deps:
    - data/raw/train.csv
    - src/preprocess/preprocess.py
    params:
    - preprocess.drop_columns
    - preprocess.missing_values_strategy
    outs:
    - data/processed/processed.csv

  train_model:
    cmd: python src/train/train_model.py --config params.yaml
    deps:
    - data/processed/processed.csv
    - src/train/train_model.py
    params:
    - train.model_params
    - train.random_state
    - train.test_size
    # outs:
    # - models/model.pkl

